export const companies = [
  {
    name: 'Tech Innovators',
    slug: 'tech-innovators',
    website: 'https://techinnovators.com',
    email: 'contact@techinnovators.com',
    phone: '+1234567890',
    address: '123 Tech Street',
    city: 'Tech City',
    state: 'TX',
    country: 'USA',
    logo: 'https://techinnovators.com/logo.png',
    description: 'Leading tech solutions provider.',
    foundedAt: new Date('2010-01-01'),
    industry: 'Technology',
    size: '100-500',
    createdByUserId: 3,
  },
  {
    name: 'HealthPlus',
    slug: 'healthplus',
    website: 'https://healthplus.com',
    email: 'info@healthplus.com',
    phone: '+1234567891',
    address: '456 Health Avenue',
    city: 'Health City',
    state: 'CA',
    country: 'USA',
    logo: 'https://healthplus.com/logo.png',
    description: 'Healthcare services and solutions.',
    foundedAt: new Date('2012-06-15'),
    industry: 'Healthcare',
    size: '50-200',
    createdByUserId: 3,
  },
  {
    name: 'EcoGreen',
    slug: 'ecogreen',
    website: 'https://ecogreen.com',
    email: 'support@ecogreen.com',
    phone: '+1234567892',
    address: '789 Green Road',
    city: 'Green City',
    state: 'WA',
    country: 'USA',
    logo: 'https://ecogreen.com/logo.png',
    description: 'Sustainable and eco-friendly products.',
    foundedAt: new Date('2015-03-23'),
    industry: 'Environmental',
    size: '10-50',
    createdByUserId: 3,
  },
  {
    name: 'FinanceHub',
    slug: 'financehub',
    website: 'https://financehub.com',
    email: 'contact@financehub.com',
    phone: '+1234567893',
    address: '321 Finance Blvd',
    city: 'Finance City',
    state: 'NY',
    country: 'USA',
    logo: 'https://financehub.com/logo.png',
    description: 'Financial consulting and services.',
    foundedAt: new Date('2018-09-30'),
    industry: 'Finance',
    size: '200-1000',
    createdByUserId: 3,
  },
  {
    name: 'EduLearn',
    slug: 'edulearn',
    website: 'https://edulearn.com',
    email: 'info@edulearn.com',
    phone: '+1234567894',
    address: '654 Learning Lane',
    city: 'Learn City',
    state: 'FL',
    country: 'USA',
    logo: 'https://edulearn.com/logo.png',
    description: 'Educational resources and training.',
    foundedAt: new Date('2011-11-11'),
    industry: 'Education',
    size: '100-500',
    createdByUserId: 3,
  },
  {
    name: 'Foodie',
    slug: 'foodie',
    website: 'https://foodie.com',
    email: 'contact@foodie.com',
    phone: '+1234567895',
    address: '987 Foodie Street',
    city: 'Food City',
    state: 'IL',
    country: 'USA',
    logo: 'https://foodie.com/logo.png',
    description: 'Gourmet food and dining experiences.',
    foundedAt: new Date('2014-07-20'),
    industry: 'Food & Beverage',
    size: '20-100',
    createdByUserId: 3,
  },
  {
    name: 'AutoMax',
    slug: 'automax',
    website: 'https://automax.com',
    email: 'support@automax.com',
    phone: '+1234567896',
    address: '135 Auto Road',
    city: 'Auto City',
    state: 'OH',
    country: 'USA',
    logo: 'https://automax.com/logo.png',
    description: 'Automotive parts and services.',
    foundedAt: new Date('2009-02-28'),
    industry: 'Automotive',
    size: '500-1000',
    createdByUserId: 3,
  },
];
